run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    # デフォルトのlint
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck

    # 追加するlint
    - gofmt
