version: "3"
services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   environment:
  #     MYSQL_HOST: host.docker.internal
  #   ports:
  #     - "8080:8080"

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_name
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/log:/var/log/mysql
  swagger:
    build: ./docker/swagger
    ports:
      - "3000:8080" # `http://localhost:3000/` で起動

