// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"app_name/api/config"
)

// Injectors from wire.go:

func InitializeApplication() (APIApplication, error) {
	configConfig, err := config.Load()
	if err != nil {
		return APIApplication{}, err
	}
	engine := setupRouter(configConfig)
	db := config.ConnectDB(configConfig)
	apiApplication := NewAPIApplication(configConfig, engine, db)
	return apiApplication, nil
}
